### ISSUE TITLE
Crash on pages where year == "-"

### ISSUE THREAD

**Issue by Sorrow2** [ramusus/kinopoiskpy#20]
На страницах, где не указан год, а стоит прочерк, скрипт вылетает.
Например:
```
>>> from kinopoisk.movie import Movie
>>> movie = Movie(id=746251)
>>> movie.get_content('main_page')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 98, in get_content
    self.get_source_instance(name).get(self)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 186, in get
    self.parse(instance, content)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/movie/sources.py", line 160, in parse
    instance.year = self.prepare_int(value.split('(')[0])
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 156, in prepare_int
    value = int(value)
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by ramusus** [comment]
0354d42..59bc188 fixed
