### ISSUE TITLE
crash when no actors listed

### ISSUE THREAD

**Issue by Sorrow2** [ramusus/kinopoiskpy#22]
```
m=kinopoisk.movie.Movie(id=926005)
m.get_content('main_page')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 98, in get_content
    self.get_source_instance(name).get(self)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 198, in get
    self.parse(instance, content)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/movie/sources.py", line 200, in parse
    for ac in actors.ul.findAll('li'):
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by ramusus** [comment]
fixed in https://github.com/ramusus/kinopoiskpy/commit/b38260c573cf3c8f33aaa088fe920784f2758b38
