### ISSUE TITLE
crash on profit

### ISSUE THREAD

**Issue by Sorrow2** [ramusus/kinopoiskpy#23]
```
>>> import kinopoisk.movie
>>> m = kinopoisk.movie.Movie(1552)
>>> m.get_content('main_page')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 98, in get_content
    self.get_source_instance(name).get(self)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 198, in get
    self.parse(instance, content)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/movie/sources.py", line 183, in parse
    instance.profit_russia = self.prepare_profit(tag.text)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 183, in prepare_profit
    return self.prepare_int(profit)
  File "/usr/local/lib/python3.4/dist-packages/kinopoisk/utils.py", line 156, in prepare_int
    value = int(value)
ValueError: invalid literal for int() with base 10: 'боры'

```

**Comment by ramusus** [comment]
fixed in b38260c..5a60d77
