### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by moran-x** [ramusus/kinopoiskpy#30]
pip3.exe install kinopoiskpy
Collecting kinopoiskpy
  Downloading kinopoiskpy-0.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\___\AppData\Local\Temp\pip-build-y59v1px5\kinopoiskpy\setup.py", line 7, in <module>
        long_description=open('README.md').read(),
      File "c:\python\python35\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1098: character maps to <undefined>

Ошибка при установке,

**Comment by ramusus** [comment]
fixed, try now
