### ISSUE TITLE
Ошибка при попытке получения данных о любом фильме

### ISSUE THREAD

**Issue by tatyanavolkova** [ramusus/kinopoiskpy#64]
Пример не работает:

>>> from kinopoisk.movie import Movie
>>> movie = Movie(id=278229)
>>> movie.get_content('main_page')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kinopoisk/utils.py", line 94, in get_content
    self.get_source_instance(name, instance=self).get()
  File "/usr/local/lib/python3.6/dist-packages/kinopoisk/utils.py", line 241, in get
    self.parse()
  File "/usr/local/lib/python3.6/dist-packages/kinopoisk/movie/sources.py", line 254, in parse
    self.instance.id = self.prepare_int(self.extract('url').split('/')[-2].split('-')[-1])
IndexError: list index out of range
>>> 

По-видимому, что-то изменилось на сайте Кинопоиска, потому что по ощущениям, еще летом (в июне) всё работало нормально.

**Comment by sandro111111** [comment]
У меня тоже не работает (

**Comment by ramusus** [comment]
Да, Кинопоиск обновил верстку и похоже кое-что сломалось. Помощь в обновлении библиотеки привествуется, т.к. времени на все не хватает

**Comment by ramusus** [comment]
Проблемы были исправлены тут https://github.com/ramusus/kinopoiskpy/pull/66
